#+TITLE: Об олимпиадном программировании в МАИ
#+OPTIONS: toc:nil num:nil author:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
#+HTML_HEAD: <style>div.figure img {max-height:300px;max-width:900px;}</style>
#+HTML_HEAD_EXTRA: <style>.org-src-container {background-color: #303030; color: #e5e5ee;}</style>
* Олимпиадные тренировки первого курса
Олимпиадные тренировки будут проводиться по пятницам каждую неделю с 16:30 в 444 аудитории ГУКа с переходом в 436, 438, 440.

Структура тренировок: лекция (1-1.5 часа), контест (2 часа), разбор контеста (1-1.5 часа). Самый главный этап остаётся на вас - дорешивание задач с контестов. Если что-то не получается, не стоит расстраиваться, лучше отдохнуть, возможно попробовать порешать что-то другое, и потом вернуться к дорешке.

По поводу списываний: я считаю, что списывание у студентов - ужасная болезнь, по типу чумы. На реальных олимпиадах вы не сможете копировать откуда-то чей-то код. Поэтому давайте так: во время тренировочных контестов вы можете обращаться только к лекциям или справочной информации по языку. Во время дорешивания уже можно обращаться к любым источникам, общаться друг с другом, обсуждать задачи, но ни в коем случае нельзя копировать чужой код. Код обязательно должен быть осмыслен и написан вами самими. Иначе будут баны.

Студенты со 2+ курсов также могут приходить послушать интересующие их темы.

** Темы осени
- C++ с азов до уровня написания нормальных олимпиад
- Математика для олимпиадного программирования
- Геометрия
- Динамическое программирование, задача о рюкзаке
- Общие часто встречающиеся алгоритмы на олимпиадах
- Ним: теория Шпрага-Гранди

** Темы весны
- NP-полные задачи
- Дерево отрезков
- Дерево отрезков с обновлениями на отрезке
- Графы: bfs, dfs, поиск циклов, топологическая сортировка
- Графы: алгоритм Форда-Беллмана, Дейкстры, Флойда-Уоршелла
- Декартово дерево
- Остовное дерево, система непересекающихся множеств
- Строковые алгоритмы, хеши
- Паросочетания, потоки

* Тренировки и олимпиады для остальных
** Опенкапы
Еженедельные командные (3 человека в команде) олимпиады на 5 часов по воскресеньям, в которых можно участвовать со 2 курса, либо, если вы уже можете решать сложные задачи, с первого. После них обычно бывает разбор силами самих участников. В этом году также вернётся дорешка.
** ICPC, MosCode, Чемпионат Урала и другие официальные соревнования
Различные региональные и международные олимпиады, на которых можно что-то выиграть и получить за это кроме славы и почёта также какие-то материальные награды или возможность получить работу в крупных компаниях.
** Контесты с Codeforces, AtCoder
На этих двух платформах каждую неделю проходят различные соревнования, в которых можно принимать участие для того, чтобы набраться опыта и научиться чему-то новому самостоятельно. Прошедшие контесты можно обсуждать в чатах телеграма.

* Что приносит олимпиадное программирование в МАИ
Во-первых, и самое главное - это умение писать программы разной степени сложности. Это пригождается на собеседованиях в различные компании, при решении каких-то реальных задач. Во-вторых, успешное выступление на официальных соревнованиях даёт прибавку к стипендии +7500 рублей. Еще можно немного поездить по городам (а то и странам) занимаясь олимпиадками. Кроме того, активное и достаточно успешное участие в олимпиадах и опенкапах даёт следующее внутри МАИ:
** 1 курс
- доп. баллы на зачёты и экзамены Зайцева В.Е.
- закрытие учебной практики
** 2 курс
- закрытие учебной практики
** 3 курс
- закрытие учебной практики
- закрытие предмета "Уравнения математической физики"
** 4 курс
- закрытие предмета "Математическое моделирование"
